# Generated by Django 6.1 on 2026-08-26 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InvestmentRecord', to='accInvestments.investments')),
            ],
        ),
    ]
