# Generated by Django 6.1 on 2026-08-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accInvestments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentrecords',
            old_name='investmentid',
            new_name='investment',
        ),
    ]
