# Generated by Django 6.1 on 2026-08-26 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accInvestments', '0002_rename_investmentid_investmentrecords_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentrecords',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
