# Generated by Django 6.1 on 2026-08-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accInvestments', '0003_investmentrecords_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentrecords',
            old_name='investment',
            new_name='investmentId',
        ),
    ]
