# Generated by Django 6.1 on 2026-08-27 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accInvestments', '0004_rename_investment_investmentrecords_investmentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentrecords',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
