# Generated by Django 6.1 on 2026-08-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accInvestments', '0005_alter_investmentrecords_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentrecords',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
