# Generated by Django 6.1 on 2026-09-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accInvestments', '0006_alter_investmentrecords_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentrecords',
            name='investmentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InvestmentName', to='accInvestments.investments'),
        ),
    ]
