# Generated by Django 6.1 on 2026-09-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accInvestments', '0007_alter_investmentrecords_investmentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentrecords',
            old_name='investmentId',
            new_name='investment',
        ),
    ]
