# Generated by Django 6.1 on 2026-08-26 09:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Savings Account', max_length=255)),
                ('startingAmount', models.DecimalField(decimal_places=2, default=1000.0, max_digits=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Transaction', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=11)),
                ('date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TransactionName', to='accSavings.accounts')),
            ],
        ),
    ]
