# Generated by Django 6.1 on 2026-08-28 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accSavings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='startingAmount',
        ),
    ]
