# Generated by Django 6.1 on 2026-09-08 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accSavings', '0002_remove_accounts_startingamount'),
        ('accountType', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='accountType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='AccountType', to='accountType.type'),
            preserve_default=False,
        ),
    ]
