# Generated by Django 6.1 on 2026-09-08 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accSavings', '0003_accounts_accounttype'),
        ('accountType', '0002_type_accumulate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='accountType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AccountType', to='accountType.type'),
        ),
    ]
