# Generated by Django 6.1 on 2026-09-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountType', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='accumulate',
            field=models.BooleanField(default=True),
        ),
    ]
